{% set name = "acro" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea1c6c3a8f93e55cc82c55232fe9d4198a4e1a1b288fd1193b13ff26890d5c58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas <=2.3.3
    - PyYAML
    - statsmodels
    - rdflib
    - tabulate

test:
  imports:
    - acro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AI-SDC/ACRO
  summary: "Tools for the Semi-Automatic Checking of Research Outputs"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
    - jim-smith
    - JessUWE
