{% set name = "acro" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4faa42f31bff3dfef100d8c9358bd5bd9439db76330c94b2ebfd551cea2b7bdc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - matplotlib-base
    - numpy
    - openpyxl
    - pandas <=2.3.3
    - PyYAML
    - statsmodels
    - rdflib
    - tabulate

test:
  imports:
    - acro
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AI-SDC/ACRO
  summary: "Tools for the Semi-Automatic Checking of Research Outputs"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rpreen
